### ISSUE TITLE
Not maintained

### ISSUE THREAD

**Issue by iceboss3d** [twopeas/multer-gcs#1]
Many of the dependencies are deprecated or no longer maintained. gcloud is now google-cloud etc.

**Comment by tmelliottjr** [comment]
Hi, thanks for the feedback!

This fork is using google-cloud, however, that too has been deprecated. [@google-cloud/storage](https://github.com/googleapis/nodejs-storage) should be used instead.

I'm working on some updates and should be able to push those changes shortly.
